name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint || true

    - name: Build
      run: npm run build

    - name: Prisma generate
      run: npm run prisma:generate

    - name: Test
      run: npm test || true
